package Quiz.QuizServerPackage;


/**
* Quiz/QuizServerPackage/answersIdsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Quiz.idl
* Freitag, 11. Oktober 2013 17:49 Uhr MESZ
*/


/* Type definition of a char sequence for the answers */
public final class answersIdsHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[] = null;

  public answersIdsHolder ()
  {
  }

  public answersIdsHolder (char[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Quiz.QuizServerPackage.answersIdsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Quiz.QuizServerPackage.answersIdsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.QuizServerPackage.answersIdsHelper.type ();
  }

}
