package Quiz.QuizServerPackage;


/**
* Quiz/QuizServerPackage/QuizException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Quiz.idl
* Freitag, 11. Oktober 2013 17:49 Uhr MESZ
*/

public final class QuizException extends org.omg.CORBA.UserException
{
  public String message = null;

  public QuizException ()
  {
    super(QuizExceptionHelper.id());
  } // ctor

  public QuizException (String _message)
  {
    super(QuizExceptionHelper.id());
    message = _message;
  } // ctor


  public QuizException (String $reason, String _message)
  {
    super(QuizExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class QuizException
