package Quiz.CompleteQuestionPackage;


/**
* Quiz/CompleteQuestionPackage/CharSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Quiz.idl
* Freitag, 11. Oktober 2013 17:49 Uhr MESZ
*/


/* Type definition of a char sequence. */
public final class CharSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[] = null;

  public CharSeqHolder ()
  {
  }

  public CharSeqHolder (char[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Quiz.CompleteQuestionPackage.CharSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Quiz.CompleteQuestionPackage.CharSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.CompleteQuestionPackage.CharSeqHelper.type ();
  }

}
