
/**
* ExampleInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../example.idl
* Wednesday, October 2, 2013 7:28:35 PM CEST
*/

public interface ExampleInterface extends ExampleInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ExampleInterface
