
/**
* ExampleInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../example.idl
* Wednesday, October 2, 2013 7:28:35 PM CEST
*/

public final class ExampleInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ExampleInterface value = null;

  public ExampleInterfaceHolder ()
  {
  }

  public ExampleInterfaceHolder (ExampleInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ExampleInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ExampleInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ExampleInterfaceHelper.type ();
  }

}
