package Quiz.QuestionPackage;


/**
* Quiz/QuestionPackage/AnswerSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Quiz.idl
* Freitag, 11. Oktober 2013 17:49 Uhr MESZ
*/

public final class AnswerSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public Quiz.Answer value[] = null;

  public AnswerSeqHolder ()
  {
  }

  public AnswerSeqHolder (Quiz.Answer[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Quiz.QuestionPackage.AnswerSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Quiz.QuestionPackage.AnswerSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.QuestionPackage.AnswerSeqHelper.type ();
  }

}
