package Quiz.QuestionPackage;


/**
* Quiz/QuestionPackage/AnswerSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Quiz.idl
* Freitag, 11. Oktober 2013 17:49 Uhr MESZ
*/

abstract public class AnswerSeqHelper
{
  private static String  _id = "IDL:Quiz/Question/AnswerSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, Quiz.Answer[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Quiz.Answer[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Quiz.AnswerHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Quiz.QuestionPackage.AnswerSeqHelper.id (), "AnswerSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Quiz.Answer[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Quiz.Answer value[] = null;
    int _len0 = istream.read_long ();
    value = new Quiz.Answer[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Quiz.AnswerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Quiz.Answer[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Quiz.AnswerHelper.write (ostream, value[_i0]);
  }

}
