package Quiz;


/**
* Quiz/Answer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Quiz.idl
* Freitag, 11. Oktober 2013 17:49 Uhr MESZ
*/


/*
	 * Data structure defining a answer for a question.
	 */
public abstract class Answer implements org.omg.CORBA.portable.StreamableValue
{
  public char id = (char)0;
  public String sentence = null;

  private static String[] _truncatable_ids = {
    Quiz.AnswerHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.id = istream.read_char ();
    this.sentence = istream.read_string ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_char (this.id);
    ostream.write_string (this.sentence);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.AnswerHelper.type ();
  }
} // class Answer
