package Quiz;


/**
* Quiz/CompleteQuestion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Quiz.idl
* Freitag, 11. Oktober 2013 17:49 Uhr MESZ
*/


/*
	 * Data structure defining a complete question. It extends the question
	 * structure by adding (multiple) correct answers.
	 */
public abstract class CompleteQuestion extends Quiz.Question
{
  public char correctAnswers[] = null;

  private static String[] _truncatable_ids = {
    Quiz.CompleteQuestionHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    super._read (istream);
    this.correctAnswers = Quiz.CompleteQuestionPackage.CharSeqHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    super._write (ostream);
    Quiz.CompleteQuestionPackage.CharSeqHelper.write (ostream, this.correctAnswers);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.CompleteQuestionHelper.type ();
  }
} // class CompleteQuestion
