package Quiz;


/**
* Quiz/QuestionDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Quiz.idl
* Freitag, 11. Oktober 2013 17:49 Uhr MESZ
*/


/*
	 * Data structure defining a question with an id, sentence and multiple
	 * answers.
	 */
public class QuestionDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new QuestionImpl ());
  }
}
