package Quiz;


/**
* Quiz/Question.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Quiz.idl
* Freitag, 11. Oktober 2013 17:49 Uhr MESZ
*/


/*
	 * Data structure defining a question with an id, sentence and multiple
	 * answers.
	 */
public abstract class Question implements org.omg.CORBA.portable.StreamableValue
{
  public int id = (int)0;
  public String sentence = null;
  public Quiz.Answer answers[] = null;

  private static String[] _truncatable_ids = {
    Quiz.QuestionHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.id = istream.read_long ();
    this.sentence = istream.read_string ();
    this.answers = Quiz.QuestionPackage.AnswerSeqHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_long (this.id);
    ostream.write_string (this.sentence);
    Quiz.QuestionPackage.AnswerSeqHelper.write (ostream, this.answers);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.QuestionHelper.type ();
  }
} // class Question
